[package]
name = "zsh-histdb-skim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "0.9.4"
rusqlite = "0.27.0"
tuikit = "0.4.5"
chrono = "0.4.19"
enum-map = "2.1.0"
log = "0.4"
textwrap = "0.15"

[dev-dependencies]
regex = "*"
